
Loaded pretrained weights for efficientnet-b0
Using triplet loss with margin:0.3
Epoch[1/100](20/481) || training loss 3.036 || training accuracy 5.78% || lr 8.32e-05
Traceback (most recent call last):
  File "/opt/conda/envs/T4039/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/T4039/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/level1_imageclassification_cv-level1-cv-15/train.py", line 242, in <module>
    train(data_dir, model_dir, cfg)
  File "/opt/ml/code/level1_imageclassification_cv-level1-cv-15/train.py", line 176, in train
    wandb.log(f" Train Epoch :{epoch},Train Loss : {train_loss}, Learning rate: {scheduler._get_lr(epoch)[0]:4.4},Train Acc: {train_acc}")
  File "/opt/conda/envs/T4039/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 292, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/T4039/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 255, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/conda/envs/T4039/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1609, in log
    self._log(data=data, step=step, commit=commit)
  File "/opt/conda/envs/T4039/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1386, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary